services:
  - type: web
    name: isl-translator
    env: python
    plan: free
    runtime: python
    pythonVersion: 3.10.13
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
